# Generated by Django 5.0.6 on 2025-06-07 02:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Reggaeton', 'Reggaeton'), ('Electronica', 'Electronica'), ('Indie', 'Indie'), ('Metal', 'Metal')], max_length=30)),
                ('alias', models.CharField(max_length=100, null=True, unique=True)),
                ('pais', models.CharField(max_length=50)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio_formacion', models.IntegerField()),
                ('genero_principal', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Reggaeton', 'Reggaeton'), ('Electronica', 'Electronica'), ('Indie', 'Indie'), ('Metal', 'Metal')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[('GT', 'Guatemala'), ('MX', 'México'), ('US', 'Estados Unidos'), ('AR', 'Argentina'), ('CO', 'Colombia'), ('ES', 'España')], max_length=3)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.evento')),
                ('hora_inicio', models.TimeField()),
            ],
            bases=('api.evento',),
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.evento')),
                ('duracion_dias', models.PositiveIntegerField()),
            ],
            bases=('api.evento',),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(choices=[('General', 'General'), ('VIP', 'VIP'), ('Preferencial', 'Preferencial'), ('Backstage', 'Backstage')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('cantidad_disponible', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamientoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipamiento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artista')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.banda')),
            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='miembros',
            field=models.ManyToManyField(through='api.MiembroBanda', to='api.artista'),
        ),
        migrations.CreateModel(
            name='ParticipacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artista')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patrocinador')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
        migrations.CreateModel(
            name='StaffEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ubicacion'),
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
        ),
    ]
