version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: evento_musical_backend
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=evento_musical_db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_pry4BD
    environment:
      POSTGRES_DB: evento_musical_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./Backend/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./Backend/02-triggers.sql:/docker-entrypoint-initdb.d/02-triggers.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d evento_musical_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_pry4BD
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: